export const APP_STATE_CHANGED = 'APP_STATE_CHANGED'

export const CONFIG_LOADED = 'CONFIG_LOADED'
export const REQUEST_CONFIG = 'REQUEST_CONFIG'

export const REQUEST_ALL_DOCUMENTS = 'REQUEST_ALL_DOCUMENTS'
export const RECEIVE_ALL_DOCUMENTS = 'RECEIVE_ALL_DOCUMENTS'

export const REQUEST_FILTER_DOCUMENTS = 'REQUEST_FILTER_DOCUMENTS'
export const RECEIVE_FILTER_DOCUMENTS = 'RECEIVE_FILTER_DOCUMENTS'
export const SET_FILTER_SELECTION = 'SET_FILTER_SELECTION'
